import { User, Song, Permission, AccessRequest, AuditLogEntry } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_super_1',
    username: 'pastor.david',
    displayName: 'Pastor David Morales',
    email: 'pastor.david@iglesia.org',
    role: 'SUPERADMIN',
    status: 'ACTIVE',
    createdAt: '2025-01-10T08:00:00Z',
    lastLoginAt: '2026-09-14T12:30:00Z',
  },
  {
    id: 'usr_admin_1',
    username: 'marta.solis',
    displayName: 'Marta Solís',
    email: 'marta.solis@iglesia.org',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2025-02-15T09:15:00Z',
    lastLoginAt: '2026-09-14T11:45:00Z',
  },
  {
    id: 'usr_admin_2',
    username: 'roberto.vega',
    displayName: 'Roberto Vega',
    email: 'roberto.vega@iglesia.org',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2025-03-01T14:20:00Z',
    lastLoginAt: '2026-09-13T18:00:00Z',
  },
  {
    id: 'usr_user_1',
    username: 'carlos.mora',
    displayName: 'Carlos Mora',
    email: 'carlos.mora@iglesia.org',
    role: 'USER',
    status: 'ACTIVE',
    createdAt: '2025-04-10T10:00:00Z',
    lastLoginAt: '2026-09-14T13:00:00Z',
  },
  {
    id: 'usr_user_2',
    username: 'elena.gomez',
    displayName: 'Elena Gómez',
    email: 'elena.gomez@iglesia.org',
    role: 'USER',
    status: 'ACTIVE',
    createdAt: '2025-05-12T16:40:00Z',
    lastLoginAt: '2026-09-14T09:10:00Z',
  },
  {
    id: 'usr_user_3',
    username: 'pedro.ramirez',
    displayName: 'Pedro Ramírez',
    email: 'pedro.ramirez@iglesia.org',
    role: 'USER',
    status: 'ACTIVE',
    createdAt: '2025-06-05T11:25:00Z',
    lastLoginAt: '2026-09-12T15:20:00Z',
  },
  {
    id: 'usr_user_4',
    username: 'lucia.fernandez',
    displayName: 'Lucía Fernández',
    email: 'lucia.fernandez@iglesia.org',
    role: 'USER',
    status: 'DISABLED',
    createdAt: '2025-07-20T13:00:00Z',
    lastLoginAt: '2026-08-01T10:00:00Z',
  },
];

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song_1',
    title: 'Gracia Sublime Es Su Amor',
    duration: '04:45',
    durationSeconds: 285,
    videoFileName: 'gracia_sublime_es_su_amor.mp4',
    fileSizeBytes: 42500000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-01-15T10:00:00Z',
    uploadedBy: 'Marta Solís',
  },
  {
    id: 'song_2',
    title: 'La Bondad de Dios (Goodness of God)',
    duration: '05:12',
    durationSeconds: 312,
    videoFileName: 'la_bondad_de_dios.mp4',
    fileSizeBytes: 48200000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-02-01T11:30:00Z',
    uploadedBy: 'Roberto Vega',
  },
  {
    id: 'song_3',
    title: 'Cuán Grande Es Él (How Great Thou Art)',
    duration: '04:18',
    durationSeconds: 258,
    videoFileName: 'cuan_grande_es_el.mp4',
    fileSizeBytes: 39100000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-02-10T14:15:00Z',
    uploadedBy: 'Marta Solís',
  },
  {
    id: 'song_4',
    title: 'Way Maker (Aquí Estás)',
    duration: '06:05',
    durationSeconds: 365,
    videoFileName: 'way_maker_aqui_estas.mp4',
    fileSizeBytes: 56300000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-02-18T16:00:00Z',
    uploadedBy: 'Pastor David Morales',
  },
  {
    id: 'song_5',
    title: 'Rey de Reyes (King of Kings)',
    duration: '04:38',
    durationSeconds: 278,
    videoFileName: 'rey_de_reyes.mp4',
    fileSizeBytes: 41800000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-03-01T09:00:00Z',
    uploadedBy: 'Marta Solís',
  },
  {
    id: 'song_6',
    title: 'Tu Fidelidad Es Grande',
    duration: '03:50',
    durationSeconds: 230,
    videoFileName: 'tu_fidelidad_es_grande.mp4',
    fileSizeBytes: 34500000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-03-10T10:30:00Z',
    uploadedBy: 'Roberto Vega',
  },
  {
    id: 'song_7',
    title: 'En Esto Creo (El Credo)',
    duration: '05:32',
    durationSeconds: 332,
    videoFileName: 'en_esto_creo_el_credo.mp4',
    fileSizeBytes: 51200000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-04-02T13:45:00Z',
    uploadedBy: 'Pastor David Morales',
  },
  {
    id: 'song_8',
    title: 'Digno y Santo (Worthy Is The Lamb)',
    duration: '05:20',
    durationSeconds: 320,
    videoFileName: 'digno_y_santo.mp4',
    fileSizeBytes: 49400000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-04-20T17:00:00Z',
    uploadedBy: 'Marta Solís',
  },
  {
    id: 'song_9',
    title: 'Mi Dios Es Tan Grande',
    duration: '02:45',
    durationSeconds: 165,
    videoFileName: 'mi_dios_es_tan_grande.mp4',
    fileSizeBytes: 26100000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-05-05T08:20:00Z',
    uploadedBy: 'Marta Solís',
  },
  {
    id: 'song_10',
    title: 'Alaba a Dios en las Alturas',
    duration: '03:40',
    durationSeconds: 220,
    videoFileName: 'alaba_a_dios_en_las_alturas.mp4',
    fileSizeBytes: 33900000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-06-12T11:00:00Z',
    uploadedBy: 'Roberto Vega',
  },
  {
    id: 'song_11',
    title: 'Noche de Paz (Especial de Navidad)',
    duration: '04:10',
    durationSeconds: 250,
    videoFileName: 'noche_de_paz.mp4',
    fileSizeBytes: 38700000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-07-01T15:30:00Z',
    uploadedBy: 'Pastor David Morales',
  },
  {
    id: 'song_12',
    title: 'Cristo Te Exalto',
    duration: '04:55',
    durationSeconds: 295,
    videoFileName: 'cristo_te_exalto.mp4',
    fileSizeBytes: 45200000,
    mimeType: 'video/mp4',
    uploadedAt: '2026-08-14T16:10:00Z',
    uploadedBy: 'Marta Solís',
  },
];

// Reference date for relative timestamps (Sept 14, 2026)
export const INITIAL_PERMISSIONS: Permission[] = [
  {
    id: 'perm_1',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_1', // Gracia Sublime Es Su Amor
    songTitle: 'Gracia Sublime Es Su Amor',
    grantedBy: 'Marta Solís',
    grantedById: 'usr_admin_1',
    grantedAt: '2026-09-14T11:00:00Z',
    startsAt: '2026-09-14T11:00:00Z',
    expiresAt: '2026-09-14T18:00:00Z', // Expires today at 6:00 PM
    status: 'ACTIVE',
  },
  {
    id: 'perm_2',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_2', // La Bondad de Dios
    songTitle: 'La Bondad de Dios (Goodness of God)',
    grantedBy: 'Pastor David Morales',
    grantedById: 'usr_super_1',
    grantedAt: '2026-09-14T12:00:00Z',
    startsAt: '2026-09-14T12:00:00Z',
    expiresAt: '2026-09-14T20:00:00Z', // Active today until 8:00 PM
    status: 'ACTIVE',
  },
  {
    id: 'perm_3',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_3', // Cuan Grande Es El
    songTitle: 'Cuán Grande Es Él (How Great Thou Art)',
    grantedBy: 'Marta Solís',
    grantedById: 'usr_admin_1',
    grantedAt: '2026-09-10T14:00:00Z',
    startsAt: '2026-09-10T14:00:00Z',
    expiresAt: '2026-09-10T18:00:00Z', // Expired
    status: 'EXPIRED',
  },
  {
    id: 'perm_4',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_5', // Rey de Reyes
    songTitle: 'Rey de Reyes (King of Kings)',
    grantedBy: 'Roberto Vega',
    grantedById: 'usr_admin_2',
    grantedAt: '2026-09-08T10:00:00Z',
    startsAt: '2026-09-08T10:00:00Z',
    expiresAt: '2026-09-08T22:00:00Z',
    status: 'REVOKED',
    revokedAt: '2026-09-08T15:30:00Z',
    revokedBy: 'Pastor David Morales',
    revocationReason: 'Cambio de orden en la reunión de Google Meet',
  },
  {
    id: 'perm_5',
    userId: 'usr_user_2', // Elena Gómez
    userName: 'Elena Gómez',
    userEmail: 'elena.gomez@iglesia.org',
    songId: 'song_9', // Mi Dios Es Tan Grande
    songTitle: 'Mi Dios Es Tan Grande',
    grantedBy: 'Marta Solís',
    grantedById: 'usr_admin_1',
    grantedAt: '2026-09-14T09:30:00Z',
    startsAt: '2026-09-14T09:30:00Z',
    expiresAt: '2026-09-14T17:30:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'perm_6',
    userId: 'usr_user_3', // Pedro Ramírez
    userName: 'Pedro Ramírez',
    userEmail: 'pedro.ramirez@iglesia.org',
    songId: 'song_4', // Way Maker
    songTitle: 'Way Maker (Aquí Estás)',
    grantedBy: 'Pastor David Morales',
    grantedById: 'usr_super_1',
    grantedAt: '2026-09-13T16:00:00Z',
    startsAt: '2026-09-13T16:00:00Z',
    expiresAt: '2026-09-13T20:00:00Z',
    status: 'EXPIRED',
  },
];

export const INITIAL_REQUESTS: AccessRequest[] = [
  {
    id: 'req_01',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    requestDate: '2026-09-14T12:15:00Z',
    meetingPurpose: 'Reunión de Oración y Discipulado Virtual',
    meetingDate: '2026-09-14T19:00:00Z',
    notes: 'Necesito esta pista de apoyo para guiar la apertura de la sala Meet de jóvenes.',
    overallStatus: 'PENDING',
    items: [
      {
        songId: 'song_4', // Way Maker
        songTitle: 'Way Maker (Aquí Estás)',
        status: 'PENDING',
      },
      {
        songId: 'song_7', // En Esto Creo
        songTitle: 'En Esto Creo (El Credo)',
        status: 'PENDING',
      },
    ],
  },
  {
    id: 'req_02',
    userId: 'usr_user_2', // Elena Gómez
    userName: 'Elena Gómez',
    userEmail: 'elena.gomez@iglesia.org',
    requestDate: '2026-09-14T09:00:00Z',
    meetingPurpose: 'Clase Virtual de Escuela Bíblica de Niños',
    meetingDate: '2026-09-14T10:00:00Z',
    notes: 'Canción interactiva para cantar con los niños en la sesión online.',
    overallStatus: 'APPROVED',
    items: [
      {
        songId: 'song_9', // Mi Dios Es Tan Grande
        songTitle: 'Mi Dios Es Tan Grande',
        status: 'APPROVED',
        reviewedBy: 'Marta Solís',
        reviewedAt: '2026-09-14T09:30:00Z',
        grantedDuration: '8 horas',
      },
    ],
  },
  {
    id: 'req_03',
    userId: 'usr_user_3', // Pedro Ramírez
    userName: 'Pedro Ramírez',
    userEmail: 'pedro.ramirez@iglesia.org',
    requestDate: '2026-09-13T14:30:00Z',
    meetingPurpose: 'Reunión de Matrimonios por Google Meet',
    meetingDate: '2026-09-13T19:30:00Z',
    notes: 'Para fondo reflexivo durante el taller de parejas.',
    overallStatus: 'APPROVED',
    items: [
      {
        songId: 'song_4', // Way Maker
        songTitle: 'Way Maker (Aquí Estás)',
        status: 'APPROVED',
        reviewedBy: 'Pastor David Morales',
        reviewedAt: '2026-09-13T16:00:00Z',
        grantedDuration: '4 horas',
      },
      {
        songId: 'song_8', // Digno y Santo
        songTitle: 'Digno y Santo (Worthy Is The Lamb)',
        status: 'REJECTED',
        reviewedBy: 'Pastor David Morales',
        reviewedAt: '2026-09-13T16:00:00Z',
        rejectionReason: 'Reservado exclusivamente para Santa Cena dominical',
      },
    ],
  },
  {
    id: 'req_04',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    requestDate: '2026-09-08T09:00:00Z',
    meetingPurpose: 'Culto de Acción de Gracias Virtual',
    overallStatus: 'APPROVED',
    items: [
      {
        songId: 'song_1',
        songTitle: 'Gracia Sublime Es Su Amor',
        status: 'APPROVED',
        reviewedBy: 'Marta Solís',
        reviewedAt: '2026-09-08T10:00:00Z',
        grantedDuration: '24 horas',
      },
      {
        songId: 'song_5',
        songTitle: 'Rey de Reyes (King of Kings)',
        status: 'APPROVED',
        reviewedBy: 'Roberto Vega',
        reviewedAt: '2026-09-08T10:00:00Z',
        grantedDuration: '12 horas',
      },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_1',
    timestamp: '2026-09-14T12:00:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Carlos Mora',
    resourceName: 'La Bondad de Dios (Goodness of God)',
    details: 'Aprobó acceso hasta hoy 8:00 PM (8 horas) para servicio virtual.',
  },
  {
    id: 'aud_2',
    timestamp: '2026-09-14T11:00:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Carlos Mora',
    resourceName: 'Gracia Sublime Es Su Amor',
    details: 'Aprobó permiso temporal de reproducción hasta hoy 6:00 PM (7 horas).',
  },
  {
    id: 'aud_3',
    timestamp: '2026-09-14T09:30:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Elena Gómez',
    resourceName: 'Mi Dios Es Tan Grande',
    details: 'Concedió acceso de 8 horas para reunión de niños en Google Meet.',
  },
  {
    id: 'aud_4',
    timestamp: '2026-09-13T16:00:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'REQUEST_REJECTED',
    actionLabel: 'Solicitud rechazada',
    affectedUser: 'Pedro Ramírez',
    resourceName: 'Digno y Santo',
    details: 'Rechazó solicitud de canción: "Reservado para Santa Cena dominical".',
  },
  {
    id: 'aud_5',
    timestamp: '2026-09-10T14:00:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Carlos Mora',
    resourceName: 'Cuán Grande Es Él',
    details: 'Concedió acceso temporal de 4 horas.',
  },
  {
    id: 'aud_6',
    timestamp: '2026-09-08T15:30:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'PERMISSION_REVOKED',
    actionLabel: 'Permiso revocado',
    affectedUser: 'Carlos Mora',
    resourceName: 'Rey de Reyes (King of Kings)',
    details: 'Revocó permiso activo. Motivo: Cambio de orden en la reunión de Google Meet.',
  },
  {
    id: 'aud_7',
    timestamp: '2026-08-14T16:10:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'VIDEO_UPLOADED',
    actionLabel: 'Video subido',
    resourceName: 'Cristo Te Exalto',
    details: 'Subió archivo MP4 protegido en biblioteca privada con letra de adoración.',
  },
  {
    id: 'aud_8',
    timestamp: '2026-08-01T10:00:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'USER_DISABLED',
    actionLabel: 'Usuario deshabilitado',
    affectedUser: 'Lucía Fernández',
    resourceName: 'lucia.fernandez@iglesia.org',
    details: 'Cuenta deshabilitada por inactividad prolongada.',
  },
  {
    id: 'aud_9',
    timestamp: '2026-06-05T11:25:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'USER_CREATED',
    actionLabel: 'Usuario creado',
    affectedUser: 'Pedro Ramírez',
    resourceName: 'pedro.ramirez@iglesia.org',
    details: 'Creó usuario regular para colaborador de alabanza.',
  },
];
