import { User, Song, Permission, AccessRequest, AuditLogEntry } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_super_1',
    username: 'pastor.david',
    displayName: 'Pastor David Morales',
    email: 'pastor.david@iglesia.org',
    role: 'SUPERADMIN',
    status: 'ACTIVE',
    createdAt: '2025-01-10T08:00:00Z',
    lastLoginAt: '2026-09-14T12:30:00Z',
  },
  {
    id: 'usr_admin_1',
    username: 'marta.solis',
    displayName: 'Marta Solís',
    email: 'marta.solis@iglesia.org',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2025-02-15T09:15:00Z',
    lastLoginAt: '2026-09-14T11:45:00Z',
  },
  {
    id: 'usr_admin_2',
    username: 'roberto.vega',
    displayName: 'Roberto Vega',
    email: 'roberto.vega@iglesia.org',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2025-03-01T14:20:00Z',
    lastLoginAt: '2026-09-13T18:00:00Z',
  },
  {
    id: 'usr_user_1',
    username: 'carlos.mora',
    displayName: 'Carlos Mora',
    email: 'carlos.mora@iglesia.org',
    role: 'USER',
    status: 'ACTIVE',
    createdAt: '2025-04-10T10:00:00Z',
    lastLoginAt: '2026-09-14T13:00:00Z',
  },
  {
    id: 'usr_user_2',
    username: 'elena.gomez',
    displayName: 'Elena Gómez',
    email: 'elena.gomez@iglesia.org',
    role: 'USER',
    status: 'ACTIVE',
    createdAt: '2025-05-12T16:40:00Z',
    lastLoginAt: '2026-09-14T09:10:00Z',
  },
  {
    id: 'usr_user_3',
    username: 'pedro.ramirez',
    displayName: 'Pedro Ramírez',
    email: 'pedro.ramirez@iglesia.org',
    role: 'USER',
    status: 'ACTIVE',
    createdAt: '2025-06-05T11:25:00Z',
    lastLoginAt: '2026-09-12T15:20:00Z',
  },
  {
    id: 'usr_user_4',
    username: 'lucia.fernandez',
    displayName: 'Lucía Fernández',
    email: 'lucia.fernandez@iglesia.org',
    role: 'USER',
    status: 'DISABLED',
    createdAt: '2025-07-20T13:00:00Z',
    lastLoginAt: '2026-08-01T10:00:00Z',
  },
];

export const INITIAL_SONGS: Song[] = [
  {
    id: 'song_1',
    title: 'Gracia Sublime Es Su Amor',
    artist: 'Phil Wickham / Traducción Comunidad',
    category: 'Alabanza',
    duration: '04:45',
    durationSeconds: 285,
    musicalKey: 'Sol Mayor (G)',
    tempoBpm: 104,
    thumbnailGradient: 'from-amber-600 to-stone-800',
    description: 'Pista con letra sincronizada de alabanza congregacional con coros dinámicos. Ideal para inicio de servicio.',
    recommendedUse: 'Apertura de reunión Google Meet',
    uploadedAt: '2026-01-15T10:00:00Z',
    uploadedBy: 'Marta Solís',
    isPrivate: true,
  },
  {
    id: 'song_2',
    title: 'La Bondad de Dios (Goodness of God)',
    artist: 'Bethel Music / Versión Español',
    category: 'Adoración',
    duration: '05:12',
    durationSeconds: 312,
    musicalKey: 'La Bemol (Ab)',
    tempoBpm: 72,
    thumbnailGradient: 'from-blue-700 to-slate-900',
    description: 'Video de adoración íntima con fondos suaves y letra de alta legibilidad para momentos de oración.',
    recommendedUse: 'Momento de intercesión y reflexión pastoral',
    uploadedAt: '2026-02-01T11:30:00Z',
    uploadedBy: 'Roberto Vega',
    isPrivate: true,
  },
  {
    id: 'song_3',
    title: 'Cuán Grande Es Él (How Great Thou Art)',
    artist: 'Himnario Cristiano Tradicional',
    category: 'Himno Clásico',
    duration: '04:18',
    durationSeconds: 258,
    musicalKey: 'Si Bemol (Bb)',
    tempoBpm: 80,
    thumbnailGradient: 'from-emerald-700 to-teal-950',
    description: 'Himno clásico solemne con orquestación moderna y fondo estético no distractor.',
    recommendedUse: 'Reunión general de domingo o santa cena',
    uploadedAt: '2026-02-10T14:15:00Z',
    uploadedBy: 'Marta Solís',
    isPrivate: true,
  },
  {
    id: 'song_4',
    title: 'Way Maker (Aquí Estás)',
    artist: 'Sinach / Darlene Zschech',
    category: 'Adoración',
    duration: '06:05',
    durationSeconds: 365,
    musicalKey: 'Mi Mayor (E)',
    tempoBpm: 68,
    thumbnailGradient: 'from-indigo-800 to-slate-950',
    description: 'Versión completa para momentos de ministración con puentes de adoración extendidos.',
    recommendedUse: 'Vigilia de oración y servicio vespertino',
    uploadedAt: '2026-02-18T16:00:00Z',
    uploadedBy: 'Pastor David Morales',
    isPrivate: true,
  },
  {
    id: 'song_5',
    title: 'Rey de Reyes (King of Kings)',
    artist: 'Hillsong Worship En Español',
    category: 'Alabanza',
    duration: '04:38',
    durationSeconds: 278,
    musicalKey: 'Re Mayor (D)',
    tempoBpm: 112,
    thumbnailGradient: 'from-red-800 to-stone-900',
    description: 'Himno teológico que narra el evangelio desde el nacimiento hasta la resurrección.',
    recommendedUse: 'Tiempo de alabanza congregacional previa al mensaje',
    uploadedAt: '2026-03-01T09:00:00Z',
    uploadedBy: 'Marta Solís',
    isPrivate: true,
  },
  {
    id: 'song_6',
    title: 'Tu Fidelidad Es Grande',
    artist: 'Miguel Cassina',
    category: 'Himno Clásico',
    duration: '03:50',
    durationSeconds: 230,
    musicalKey: 'Do Mayor (C)',
    tempoBpm: 76,
    thumbnailGradient: 'from-cyan-800 to-slate-900',
    description: 'Cántico congregacional tradicional, arreglos de piano y cuerdas para devocionales matutinos.',
    recommendedUse: 'Devocional semanal y reuniones de estudio bíblico',
    uploadedAt: '2026-03-10T10:30:00Z',
    uploadedBy: 'Roberto Vega',
    isPrivate: true,
  },
  {
    id: 'song_7',
    title: 'En Esto Creo (El Credo)',
    artist: 'Hillsong En Español',
    category: 'Adoración',
    duration: '05:32',
    durationSeconds: 332,
    musicalKey: 'Fa Mayor (F)',
    tempoBpm: 70,
    thumbnailGradient: 'from-purple-900 to-slate-950',
    description: 'Declaración bíblica de fe trinitaria. Recomendada para servicios de bautismos o profesión de fe.',
    recommendedUse: 'Servicio dominical y conferencias',
    uploadedAt: '2026-04-02T13:45:00Z',
    uploadedBy: 'Pastor David Morales',
    isPrivate: true,
  },
  {
    id: 'song_8',
    title: 'Digno y Santo (Worthy Is The Lamb)',
    artist: 'Kari Jobe / Trad. Iglesia',
    category: 'Comunión',
    duration: '05:20',
    durationSeconds: 320,
    musicalKey: 'Sol Mayor (G)',
    tempoBpm: 66,
    thumbnailGradient: 'from-rose-800 to-slate-900',
    description: 'Canción reverente especial para el servicio de Santa Cena y memoria del sacrificio de Cristo.',
    recommendedUse: 'Servicio de Santa Cena el primer domingo de mes',
    uploadedAt: '2026-04-20T17:00:00Z',
    uploadedBy: 'Marta Solís',
    isPrivate: true,
  },
  {
    id: 'song_9',
    title: 'Mi Dios Es Tan Grande',
    artist: 'Ministerio Infantil Bethel',
    category: 'Especial Niños',
    duration: '02:45',
    durationSeconds: 165,
    musicalKey: 'Re Mayor (D)',
    tempoBpm: 124,
    thumbnailGradient: 'from-amber-700 to-yellow-900',
    description: 'Canción animada con letra colorida y movimientos para la clase infantil virtual por Meet.',
    recommendedUse: 'Escuela Bíblica Infantil virtual en Meet',
    uploadedAt: '2026-05-05T08:20:00Z',
    uploadedBy: 'Marta Solís',
    isPrivate: true,
  },
  {
    id: 'song_10',
    title: 'Alaba a Dios en las Alturas',
    artist: 'Marcos Witt / Clásicos',
    category: 'Alabanza',
    duration: '03:40',
    durationSeconds: 220,
    musicalKey: 'Mi Menor (Em)',
    tempoBpm: 120,
    thumbnailGradient: 'from-teal-800 to-slate-900',
    description: 'Pista rítmica y alegre para celebración y bienvenida de la comunidad en línea.',
    recommendedUse: 'Apertura y bienvenida dominical',
    uploadedAt: '2026-06-12T11:00:00Z',
    uploadedBy: 'Roberto Vega',
    isPrivate: true,
  },
  {
    id: 'song_11',
    title: 'Noche de Paz (Especial de Navidad)',
    artist: 'Coro Congregacional',
    category: 'Himno Clásico',
    duration: '04:10',
    durationSeconds: 250,
    musicalKey: 'Si Bemol (Bb)',
    tempoBpm: 65,
    thumbnailGradient: 'from-blue-900 to-indigo-950',
    description: 'Arreglo acústico coral con iluminación cálida. Video masterizado en 1080p.',
    recommendedUse: 'Temporada navideña y cultos especiales de fin de año',
    uploadedAt: '2026-07-01T15:30:00Z',
    uploadedBy: 'Pastor David Morales',
    isPrivate: true,
  },
  {
    id: 'song_12',
    title: 'Cristo Te Exalto',
    artist: 'Clásicos de Adoración',
    category: 'Adoración',
    duration: '04:55',
    durationSeconds: 295,
    musicalKey: 'Fa Mayor (F)',
    tempoBpm: 74,
    thumbnailGradient: 'from-slate-800 to-zinc-950',
    description: 'Adoración solemne enfocada en la majestad de Dios. Ideal para transiciones de sermón.',
    recommendedUse: 'Transición previa a la predicación de la Palabra',
    uploadedAt: '2026-08-14T16:10:00Z',
    uploadedBy: 'Marta Solís',
    isPrivate: true,
  },
];

// Reference date for relative timestamps (Sept 14, 2026)
export const INITIAL_PERMISSIONS: Permission[] = [
  {
    id: 'perm_1',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_1', // Gracia Sublime Es Su Amor
    songTitle: 'Gracia Sublime Es Su Amor',
    grantedBy: 'Marta Solís',
    grantedById: 'usr_admin_1',
    grantedAt: '2026-09-14T11:00:00Z',
    startsAt: '2026-09-14T11:00:00Z',
    expiresAt: '2026-09-14T18:00:00Z', // Expires today at 6:00 PM
    status: 'ACTIVE',
  },
  {
    id: 'perm_2',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_2', // La Bondad de Dios
    songTitle: 'La Bondad de Dios (Goodness of God)',
    grantedBy: 'Pastor David Morales',
    grantedById: 'usr_super_1',
    grantedAt: '2026-09-14T12:00:00Z',
    startsAt: '2026-09-14T12:00:00Z',
    expiresAt: '2026-09-14T20:00:00Z', // Active today until 8:00 PM
    status: 'ACTIVE',
  },
  {
    id: 'perm_3',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_3', // Cuan Grande Es El
    songTitle: 'Cuán Grande Es Él (How Great Thou Art)',
    grantedBy: 'Marta Solís',
    grantedById: 'usr_admin_1',
    grantedAt: '2026-09-10T14:00:00Z',
    startsAt: '2026-09-10T14:00:00Z',
    expiresAt: '2026-09-10T18:00:00Z', // Expired
    status: 'EXPIRED',
  },
  {
    id: 'perm_4',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    songId: 'song_5', // Rey de Reyes
    songTitle: 'Rey de Reyes (King of Kings)',
    grantedBy: 'Roberto Vega',
    grantedById: 'usr_admin_2',
    grantedAt: '2026-09-08T10:00:00Z',
    startsAt: '2026-09-08T10:00:00Z',
    expiresAt: '2026-09-08T22:00:00Z',
    status: 'REVOKED',
    revokedAt: '2026-09-08T15:30:00Z',
    revokedBy: 'Pastor David Morales',
    revocationReason: 'Cambio de orden en la reunión de Google Meet',
  },
  {
    id: 'perm_5',
    userId: 'usr_user_2', // Elena Gómez
    userName: 'Elena Gómez',
    userEmail: 'elena.gomez@iglesia.org',
    songId: 'song_9', // Mi Dios Es Tan Grande
    songTitle: 'Mi Dios Es Tan Grande',
    grantedBy: 'Marta Solís',
    grantedById: 'usr_admin_1',
    grantedAt: '2026-09-14T09:30:00Z',
    startsAt: '2026-09-14T09:30:00Z',
    expiresAt: '2026-09-14T17:30:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'perm_6',
    userId: 'usr_user_3', // Pedro Ramírez
    userName: 'Pedro Ramírez',
    userEmail: 'pedro.ramirez@iglesia.org',
    songId: 'song_4', // Way Maker
    songTitle: 'Way Maker (Aquí Estás)',
    grantedBy: 'Pastor David Morales',
    grantedById: 'usr_super_1',
    grantedAt: '2026-09-13T16:00:00Z',
    startsAt: '2026-09-13T16:00:00Z',
    expiresAt: '2026-09-13T20:00:00Z',
    status: 'EXPIRED',
  },
];

export const INITIAL_REQUESTS: AccessRequest[] = [
  {
    id: 'REQ-2026-081',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    requestDate: '2026-09-14T12:15:00Z',
    meetingPurpose: 'Reunión de Oración y Discipulado Virtual',
    meetingDate: '2026-09-14T19:00:00Z',
    notes: 'Necesito esta pista de apoyo para guiar la apertura de la sala Meet de jóvenes.',
    overallStatus: 'PENDING',
    items: [
      {
        songId: 'song_4', // Way Maker
        songTitle: 'Way Maker (Aquí Estás)',
        status: 'PENDING',
      },
      {
        songId: 'song_7', // En Esto Creo
        songTitle: 'En Esto Creo (El Credo)',
        status: 'PENDING',
      },
    ],
  },
  {
    id: 'REQ-2026-079',
    userId: 'usr_user_2', // Elena Gómez
    userName: 'Elena Gómez',
    userEmail: 'elena.gomez@iglesia.org',
    requestDate: '2026-09-14T09:00:00Z',
    meetingPurpose: 'Clase Virtual de Escuela Bíblica de Niños',
    meetingDate: '2026-09-14T10:00:00Z',
    notes: 'Canción interactiva para cantar con los niños en la sesión online.',
    overallStatus: 'APPROVED',
    items: [
      {
        songId: 'song_9', // Mi Dios Es Tan Grande
        songTitle: 'Mi Dios Es Tan Grande',
        status: 'APPROVED',
        reviewedBy: 'Marta Solís',
        reviewedAt: '2026-09-14T09:30:00Z',
        grantedDuration: '8 horas',
      },
    ],
  },
  {
    id: 'REQ-2026-075',
    userId: 'usr_user_3', // Pedro Ramírez
    userName: 'Pedro Ramírez',
    userEmail: 'pedro.ramirez@iglesia.org',
    requestDate: '2026-09-13T14:30:00Z',
    meetingPurpose: 'Reunión de Matrimonios por Google Meet',
    meetingDate: '2026-09-13T19:30:00Z',
    notes: 'Para fondo reflexivo durante el taller de parejas.',
    overallStatus: 'APPROVED',
    items: [
      {
        songId: 'song_4', // Way Maker
        songTitle: 'Way Maker (Aquí Estás)',
        status: 'APPROVED',
        reviewedBy: 'Pastor David Morales',
        reviewedAt: '2026-09-13T16:00:00Z',
        grantedDuration: '4 horas',
      },
      {
        songId: 'song_8', // Digno y Santo
        songTitle: 'Digno y Santo (Worthy Is The Lamb)',
        status: 'REJECTED',
        reviewedBy: 'Pastor David Morales',
        reviewedAt: '2026-09-13T16:00:00Z',
        rejectionReason: 'Reservado exclusivamente para Santa Cena dominical',
      },
    ],
  },
  {
    id: 'REQ-2026-070',
    userId: 'usr_user_1', // Carlos Mora
    userName: 'Carlos Mora',
    userEmail: 'carlos.mora@iglesia.org',
    requestDate: '2026-09-08T09:00:00Z',
    meetingPurpose: 'Culto de Acción de Gracias Virtual',
    overallStatus: 'APPROVED',
    items: [
      {
        songId: 'song_1',
        songTitle: 'Gracia Sublime Es Su Amor',
        status: 'APPROVED',
        reviewedBy: 'Marta Solís',
        reviewedAt: '2026-09-08T10:00:00Z',
        grantedDuration: '24 horas',
      },
      {
        songId: 'song_5',
        songTitle: 'Rey de Reyes (King of Kings)',
        status: 'APPROVED',
        reviewedBy: 'Roberto Vega',
        reviewedAt: '2026-09-08T10:00:00Z',
        grantedDuration: '12 horas',
      },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud_1',
    timestamp: '2026-09-14T12:00:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Carlos Mora',
    resourceName: 'La Bondad de Dios (Goodness of God)',
    details: 'Aprobó acceso hasta hoy 8:00 PM (8 horas) para servicio virtual.',
  },
  {
    id: 'aud_2',
    timestamp: '2026-09-14T11:00:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Carlos Mora',
    resourceName: 'Gracia Sublime Es Su Amor',
    details: 'Aprobó permiso temporal de reproducción hasta hoy 6:00 PM (7 horas).',
  },
  {
    id: 'aud_3',
    timestamp: '2026-09-14T09:30:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Elena Gómez',
    resourceName: 'Mi Dios Es Tan Grande',
    details: 'Concedió acceso de 8 horas para reunión de niños en Google Meet.',
  },
  {
    id: 'aud_4',
    timestamp: '2026-09-13T16:00:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'REQUEST_REJECTED',
    actionLabel: 'Solicitud rechazada',
    affectedUser: 'Pedro Ramírez',
    resourceName: 'Digno y Santo',
    details: 'Rechazó canción en REQ-2026-075: "Reservado para Santa Cena dominical".',
  },
  {
    id: 'aud_5',
    timestamp: '2026-09-10T14:00:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'REQUEST_APPROVED',
    actionLabel: 'Acceso aprobado',
    affectedUser: 'Carlos Mora',
    resourceName: 'Cuán Grande Es Él',
    details: 'Concedió acceso temporal de 4 horas.',
  },
  {
    id: 'aud_6',
    timestamp: '2026-09-08T15:30:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'PERMISSION_REVOKED',
    actionLabel: 'Permiso revocado',
    affectedUser: 'Carlos Mora',
    resourceName: 'Rey de Reyes (King of Kings)',
    details: 'Revocó permiso activo. Motivo: Cambio de orden en la reunión de Google Meet.',
  },
  {
    id: 'aud_7',
    timestamp: '2026-08-14T16:10:00Z',
    actorName: 'Marta Solís',
    actorRole: 'ADMIN',
    action: 'VIDEO_UPLOADED',
    actionLabel: 'Video subido',
    resourceName: 'Cristo Te Exalto',
    details: 'Subió archivo MP4 protegido en biblioteca privada con letra de adoración.',
  },
  {
    id: 'aud_8',
    timestamp: '2026-08-01T10:00:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'USER_DISABLED',
    actionLabel: 'Usuario deshabilitado',
    affectedUser: 'Lucía Fernández',
    resourceName: 'lucia.fernandez@iglesia.org',
    details: 'Cuenta deshabilitada por inactividad prolongada.',
  },
  {
    id: 'aud_9',
    timestamp: '2026-06-05T11:25:00Z',
    actorName: 'Pastor David Morales',
    actorRole: 'SUPERADMIN',
    action: 'USER_CREATED',
    actionLabel: 'Usuario creado',
    affectedUser: 'Pedro Ramírez',
    resourceName: 'pedro.ramirez@iglesia.org',
    details: 'Creó usuario regular para colaborador de alabanza.',
  },
];
